### ISSUE TITLE
Implement download_rgba_scaled method for wgpu rendering backend

### ISSUE THREAD

**Issue by ezioleq** [netcanv/netcanv#233]
On the `master` branch, the `download_rgba_scaled` method introduced by #227 is not implemented in `wgpu-renderer` which prevents the backend from compiling. You can see the error in the build log.

```rs
error[E0046]: not all trait items implemented, missing: `download_framebuffer_scaled`
   --> netcanv-renderer-wgpu/src/rendering.rs:332:1
    |
332 | impl RenderBackend for WgpuBackend {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `download_framebuffer_scaled` in implementation
    |
    = help: implement the missing item: `fn download_framebuffer_scaled(&mut self, _: &<Self as RenderBackend>::Framebuffer, _: (u32, u32), _: (u32, u32), _: &mut [u8]) { todo!() }`
```

This functionality is crucial for the selection-to-clipboard coping mechanism.
